language: android

android:
  components:
    - build-tools-23.0.0
    - android-23
    - sys-img-armeabi-v7a-android-23
    - extra-android-m2repository


before_script:
  - sudo apt-get update
  - sudo apt-get install -u lib32stdc++6 lib32z1

script:
    - echo hola
