sudo: false
language: android
android:
  components:
  - platform-tools
  - build-tools-23.0.2
  - build-tools-24.3.3
  - android-23
  - sys-img-armeabi-v7a-android-23
  - extra-android-m2repository
script:
  - echo $ADB_INSTALL_TIMEOUT
  - echo hola
