language: android
android:
  components:
  - tools
  - build-tools-23.0.2
  - android-23
  - android-24
  - sys-img-armeabi-v7a-android-23
  - extra-android-m2repository
script:
  - echo $ADB_INSTALL_TIMEOUT
notifications:
  email:
    recipients:
      - secure: alDb12u8w+f/vGSz29ayVp9OEQLcqpmDXaKifc5u3nHaW9u3Ot6OBrNL0kioBcwXajRK9NMG1f8Yx9IjOMHT6dc2uBFHn4q2Q6cP8nJhiyVyBD5YglsPwpyCOx6eEVSBCRsekVwqUZES61cxdBd1gCUzuMldnLxfGavR+G1Xxg6Zxu8CeVa6n3oJ8XEUg9t3MuVqTypYR+YdzmgvAI+m4p5zDICBQybNw3OQt0KPyvkUqhwDHOj2luJP1Z5G+CewVBPUf4JyF+RMCBQI+4Xs0XDJWA8KAWfVshbfpekCipuazSrW+GeX9pqpdrDWVUYoD+bPgpAzL5dghzi8qt27q9x0AsUiNEvZqkbYTxsPNJ2iFqTL0Cg87sBBveT1f4tO98xImWVMc3j+E+txkSlAMWqmVzVYEDVvo/HWdCN0cTlzH8sfU0+ByRV5vqILVFiJ2GuRWjWqcKyU0vACAZvySjxNj7BBax7wxmeZCDRl5TjmwULB1LsfzQlCxxcsFSjxloCZaLwFg6cXfiogrYOHirwm8lP8ifHIuI44dgWb1BM5e3chMWIOPLYbFHef2zgZrcZ06ZCzU7zK1Ux19L96NqsPfm0DiBbfd8czE5OystSMUigLNYHe84MCY+z1lQLgRAkrXy1eK5gN7gEN4ONzUQXLUf8pUU/FlLpADYxiXHM=
  on_success: always
  on_failure: always
