language: android
android:
  components:
  - build-tools-23.0.0
  - android-23
  - sys-img-armeabi-v7a-android-23
  - extra-android-m2repository
script:
- echo hola
- echo $EMAIL_NOTIFICATION
notifications:
  email:
    recipients:
    - maria@travis-ci.com
    - $EMAIL_NOTIFICATION
    on_success: always
    on_failure: always
env:
  global:
    secure: c53KDbg8u+5Qkzi4br0NmxmuCjwjuitIF8o2N5vWUwgMchsZT15AoTTsh9MhYdO+rikl36YCK9BSo9uMMzcAOsIHTtehiaA1O0EXMip0fQNjyWKEUHJ42Txy/bKyAtBSgl17OOihVYI1LTx+rHBTh/zWPwzEaUrdd49Yg/As0lpdSL4nk/uFm3RcLWpYRDDNCFYecx9OARgpmU/A8V3qiQ4nA7DpeNp5fuUJPT1YoTvK0Ha3jGNKQRSg9mZYwUn8s9u9LAI1BBNZ/Ewu0aMy9W37ywthn41ltc9m8NQe6arYaH1l99Pnuu3PixgExEhGPwojvFrmPLbckaJPr4EWC1+Xv5aU4napZAxZ6DVIxsLdHCbuFz3cWOvatCXsVb2oJKorP8K2KggfFReEqRRJiH3ewG9pBqdgpReBvexjkHBp4EIUyKulsXWkc+Mu+9bhew9WnWhaeVa5XCNtr21l2MqL7iteLtGArjTWmtFVfWG85InR76iAODzJQ6wxl+OkyGL6bADOLnpWR9+X92D01PLSX6Ry7vi+mVTWSSVVhmwaMaaZgwU6+BBEGY7eSPKV9gjpiY0QQwVkwV/J/YHhXu9ekISU6wuyXcCN3o0tKxUTz5jhY3W4QWUy75LFMxEGjkzP211CYqNtWAD8c4skBHzx+CI6dDDcGdIdAssQILQ=
